const BLUE_PLUS = 1
const YELLOW_ROUND_PLUS = 2
const GREEN_CIRCLE = 3
const PINK_SHARP_PLUS = 4
const OCTAGON = 5
const YELLOW_CIRCLE = 6
const PINK_SQUARE_PLUS = 7
const ORANGE_ROUND_PLUS = 8
const YELLOW_FLOWER = 9
const BLUE_SHARP_PLUS = 10
const ORANGE_SHARP_PLUS = 11
const DARK_BLUE_SQUARE_PLUS = 12
const ORANGE_FLOWER = 13
const PINK_ROUND_PLUS = 14
const GREEN_SQUARE = 15
const BLUE_SQUARE = 16
const PINK_DIAMOND = 17
const BLUE_STAR = 18
const YELLOW_STAR = 19
const PURPLE_STAR = 20
const YELLOW_SQUARE_PLUS = 21
const PINK_CIRCLE = 22
const BOARD = 0

const SQUARES_DB = [
  { id: 1, type: BLUE_PLUS },
  { id: 2, type: YELLOW_ROUND_PLUS },
  { id: 3, type: GREEN_CIRCLE },
  { id: 4, type: PINK_SHARP_PLUS },
  { id: 5, type: OCTAGON },
  { id: 6, type: YELLOW_CIRCLE },
  { id: 7, type: PINK_SQUARE_PLUS },
  { id: 8, type: ORANGE_ROUND_PLUS },
  { id: 9, type: YELLOW_FLOWER },
  { id: 10, type: BLUE_SHARP_PLUS },
  { id: 11, type: ORANGE_SHARP_PLUS },
  { id: 12, type: DARK_BLUE_SQUARE_PLUS },
  { id: 13, type: ORANGE_FLOWER },
  { id: 14, type: PINK_ROUND_PLUS },
  { id: 15, type: GREEN_SQUARE },
  { id: 16, type: BLUE_SQUARE },
  { id: 17, type: PINK_DIAMOND },
  { id: 18, type: BLUE_STAR },
  { id: 19, type: YELLOW_STAR },
  { id: 20, type: PURPLE_STAR },
  { id: 21, type: YELLOW_SQUARE_PLUS },
  { id: 22, type: PINK_CIRCLE },
]

const PIECES_DB = [
  { id: 1, left: BOARD, top: BLUE_PLUS, right: PINK_DIAMOND, bottom: BOARD },
  { id: 2, left: BOARD, top: BLUE_PLUS, right: OCTAGON, bottom: BOARD },
  {
    id: 3,
    left: BOARD,
    top: YELLOW_FLOWER,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },
  {
    id: 4,
    left: BOARD,
    top: PINK_DIAMOND,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },

  {
    id: 5,
    left: BLUE_PLUS,
    top: YELLOW_ROUND_PLUS,
    right: BLUE_PLUS,
    bottom: BOARD,
  },
  {
    id: 6,
    left: BLUE_PLUS,
    top: BLUE_SHARP_PLUS,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 7,
    left: BLUE_PLUS,
    top: YELLOW_CIRCLE,
    right: BLUE_PLUS,
    bottom: BOARD,
  },
  {
    id: 8,
    left: BLUE_PLUS,
    top: YELLOW_CIRCLE,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },

  {
    id: 9,
    left: BLUE_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },
  {
    id: 10,
    left: BLUE_PLUS,
    top: PINK_SQUARE_PLUS,
    right: OCTAGON,
    bottom: BOARD,
  },
  {
    id: 11,
    left: BLUE_PLUS,
    top: GREEN_SQUARE,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 12,
    left: BLUE_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: OCTAGON,
    bottom: BOARD,
  },

  {
    id: 13,
    left: BLUE_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 14,
    left: BLUE_PLUS,
    top: YELLOW_SQUARE_PLUS,
    right: OCTAGON,
    bottom: BOARD,
  },
  {
    id: 15,
    left: YELLOW_FLOWER,
    top: BLUE_SHARP_PLUS,
    right: BLUE_PLUS,
    bottom: BOARD,
  },
  {
    id: 16,
    left: YELLOW_FLOWER,
    top: BLUE_STAR,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },

  {
    id: 17,
    left: YELLOW_FLOWER,
    top: PINK_ROUND_PLUS,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 18,
    left: YELLOW_FLOWER,
    top: YELLOW_STAR,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 19,
    left: YELLOW_FLOWER,
    top: PINK_SQUARE_PLUS,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 20,
    left: YELLOW_FLOWER,
    top: GREEN_SQUARE,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },

  {
    id: 21,
    left: YELLOW_FLOWER,
    top: PINK_SHARP_PLUS,
    right: OCTAGON,
    bottom: BOARD,
  },
  {
    id: 22,
    left: YELLOW_FLOWER,
    top: DARK_BLUE_SQUARE_PLUS,
    right: BLUE_PLUS,
    bottom: BOARD,
  },
  {
    id: 23,
    left: YELLOW_FLOWER,
    top: DARK_BLUE_SQUARE_PLUS,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 24,
    left: YELLOW_FLOWER,
    top: PURPLE_STAR,
    right: BLUE_PLUS,
    bottom: BOARD,
  },

  {
    id: 25,
    left: YELLOW_FLOWER,
    top: YELLOW_SQUARE_PLUS,
    right: BLUE_PLUS,
    bottom: BOARD,
  },
  {
    id: 26,
    left: PINK_DIAMOND,
    top: YELLOW_ROUND_PLUS,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 27,
    left: PINK_DIAMOND,
    top: YELLOW_ROUND_PLUS,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },
  {
    id: 28,
    left: PINK_DIAMOND,
    top: BLUE_SHARP_PLUS,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },

  {
    id: 29,
    left: PINK_DIAMOND,
    top: BLUE_STAR,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },
  {
    id: 30,
    left: PINK_DIAMOND,
    top: PINK_SQUARE_PLUS,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 31,
    left: PINK_DIAMOND,
    top: GREEN_SQUARE,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 32,
    left: PINK_DIAMOND,
    top: PURPLE_STAR,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },

  {
    id: 33,
    left: PINK_DIAMOND,
    top: ORANGE_ROUND_PLUS,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 34,
    left: PINK_DIAMOND,
    top: ORANGE_ROUND_PLUS,
    right: OCTAGON,
    bottom: BOARD,
  },
  {
    id: 35,
    left: PINK_DIAMOND,
    top: BLUE_SQUARE,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 36,
    left: PINK_DIAMOND,
    top: PINK_CIRCLE,
    right: OCTAGON,
    bottom: BOARD,
  },

  { id: 37, left: OCTAGON, top: BLUE_STAR, right: BLUE_PLUS, bottom: BOARD },
  {
    id: 38,
    left: OCTAGON,
    top: GREEN_CIRCLE,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 39,
    left: OCTAGON,
    top: ORANGE_SHARP_PLUS,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 40,
    left: OCTAGON,
    top: YELLOW_STAR,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },

  {
    id: 41,
    left: OCTAGON,
    top: YELLOW_STAR,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },
  { id: 42, left: OCTAGON, top: GREEN_SQUARE, right: BLUE_PLUS, bottom: BOARD },
  {
    id: 43,
    left: OCTAGON,
    top: GREEN_SQUARE,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 44,
    left: OCTAGON,
    top: GREEN_SQUARE,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },

  {
    id: 45,
    left: OCTAGON,
    top: PINK_SHARP_PLUS,
    right: BLUE_PLUS,
    bottom: BOARD,
  },
  { id: 46, left: OCTAGON, top: PURPLE_STAR, right: OCTAGON, bottom: BOARD },
  {
    id: 47,
    left: OCTAGON,
    top: ORANGE_ROUND_PLUS,
    right: OCTAGON,
    bottom: BOARD,
  },
  { id: 48, left: OCTAGON, top: BLUE_SQUARE, right: OCTAGON, bottom: BOARD },

  {
    id: 49,
    left: ORANGE_FLOWER,
    top: YELLOW_ROUND_PLUS,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 50,
    left: ORANGE_FLOWER,
    top: BLUE_SHARP_PLUS,
    right: BLUE_PLUS,
    bottom: BOARD,
  },
  {
    id: 51,
    left: ORANGE_FLOWER,
    top: BLUE_SHARP_PLUS,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 52,
    left: ORANGE_FLOWER,
    top: YELLOW_CIRCLE,
    right: BLUE_PLUS,
    bottom: BOARD,
  },

  {
    id: 53,
    left: ORANGE_FLOWER,
    top: PINK_SQUARE_PLUS,
    right: OCTAGON,
    bottom: BOARD,
  },
  {
    id: 54,
    left: ORANGE_FLOWER,
    top: PINK_SHARP_PLUS,
    right: OCTAGON,
    bottom: BOARD,
  },
  {
    id: 55,
    left: ORANGE_FLOWER,
    top: PINK_SHARP_PLUS,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 56,
    left: ORANGE_FLOWER,
    top: ORANGE_ROUND_PLUS,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },

  {
    id: 57,
    left: ORANGE_FLOWER,
    top: BLUE_SQUARE,
    right: BLUE_PLUS,
    bottom: BOARD,
  },
  {
    id: 58,
    left: ORANGE_FLOWER,
    top: BLUE_SQUARE,
    right: ORANGE_FLOWER,
    bottom: BOARD,
  },
  {
    id: 59,
    left: ORANGE_FLOWER,
    top: YELLOW_SQUARE_PLUS,
    right: YELLOW_FLOWER,
    bottom: BOARD,
  },
  {
    id: 60,
    left: ORANGE_FLOWER,
    top: PINK_CIRCLE,
    right: PINK_DIAMOND,
    bottom: BOARD,
  },

  {
    id: 61,
    left: YELLOW_ROUND_PLUS,
    top: YELLOW_CIRCLE,
    right: BLUE_STAR,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 62,
    left: YELLOW_ROUND_PLUS,
    top: PINK_ROUND_PLUS,
    right: PINK_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 63,
    left: BLUE_SHARP_PLUS,
    top: BLUE_SHARP_PLUS,
    right: GREEN_CIRCLE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 64,
    left: BLUE_STAR,
    top: YELLOW_ROUND_PLUS,
    right: ORANGE_ROUND_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 65,
    left: BLUE_STAR,
    top: BLUE_STAR,
    right: PINK_CIRCLE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 66,
    left: BLUE_STAR,
    top: PINK_ROUND_PLUS,
    right: PINK_ROUND_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 67,
    left: BLUE_STAR,
    top: ORANGE_SHARP_PLUS,
    right: BLUE_SHARP_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 68,
    left: BLUE_STAR,
    top: PURPLE_STAR,
    right: YELLOW_CIRCLE,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 69,
    left: BLUE_STAR,
    top: PINK_CIRCLE,
    right: ORANGE_ROUND_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 70,
    left: GREEN_CIRCLE,
    top: GREEN_CIRCLE,
    right: PINK_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 71,
    left: GREEN_CIRCLE,
    top: PINK_SQUARE_PLUS,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 72,
    left: ORANGE_SHARP_PLUS,
    top: PINK_ROUND_PLUS,
    right: BLUE_STAR,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 73,
    left: ORANGE_SHARP_PLUS,
    top: GREEN_SQUARE,
    right: PINK_SHARP_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 74,
    left: ORANGE_SHARP_PLUS,
    top: PURPLE_STAR,
    right: GREEN_SQUARE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 75,
    left: ORANGE_SHARP_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: GREEN_CIRCLE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 76,
    left: YELLOW_STAR,
    top: PINK_ROUND_PLUS,
    right: GREEN_SQUARE,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 77,
    left: YELLOW_STAR,
    top: YELLOW_STAR,
    right: GREEN_SQUARE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 78,
    left: PINK_SQUARE_PLUS,
    top: GREEN_CIRCLE,
    right: BLUE_SQUARE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 79,
    left: PINK_SQUARE_PLUS,
    top: PURPLE_STAR,
    right: GREEN_CIRCLE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 80,
    left: PINK_SQUARE_PLUS,
    top: BLUE_SQUARE,
    right: YELLOW_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 81,
    left: GREEN_SQUARE,
    top: YELLOW_STAR,
    right: BLUE_STAR,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 82,
    left: PINK_SHARP_PLUS,
    top: BLUE_STAR,
    right: BLUE_STAR,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 83,
    left: PINK_SHARP_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: PINK_SHARP_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 84,
    left: DARK_BLUE_SQUARE_PLUS,
    top: BLUE_STAR,
    right: YELLOW_STAR,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 85,
    left: DARK_BLUE_SQUARE_PLUS,
    top: YELLOW_CIRCLE,
    right: PINK_ROUND_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 86,
    left: DARK_BLUE_SQUARE_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 87,
    left: DARK_BLUE_SQUARE_PLUS,
    top: BLUE_SQUARE,
    right: PURPLE_STAR,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 88,
    left: PURPLE_STAR,
    top: YELLOW_ROUND_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 89,
    left: PURPLE_STAR,
    top: YELLOW_CIRCLE,
    right: PINK_CIRCLE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 90,
    left: PURPLE_STAR,
    top: PINK_SHARP_PLUS,
    right: BLUE_SQUARE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 91,
    left: ORANGE_ROUND_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 92,
    left: ORANGE_ROUND_PLUS,
    top: YELLOW_STAR,
    right: GREEN_SQUARE,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 93,
    left: ORANGE_ROUND_PLUS,
    top: YELLOW_STAR,
    right: PINK_SHARP_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 94,
    left: ORANGE_ROUND_PLUS,
    top: PINK_SHARP_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 95,
    left: ORANGE_ROUND_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: PINK_ROUND_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 96,
    left: YELLOW_SQUARE_PLUS,
    top: YELLOW_SQUARE_PLUS,
    right: GREEN_CIRCLE,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 97,
    left: PINK_CIRCLE,
    top: PINK_SHARP_PLUS,
    right: YELLOW_STAR,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 98,
    left: PINK_CIRCLE,
    top: PURPLE_STAR,
    right: ORANGE_ROUND_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 99,
    left: PINK_CIRCLE,
    top: YELLOW_SQUARE_PLUS,
    right: YELLOW_CIRCLE,
    bottom: YELLOW_ROUND_PLUS,
  },
  {
    id: 100,
    left: PINK_CIRCLE,
    top: PINK_CIRCLE,
    right: YELLOW_SQUARE_PLUS,
    bottom: YELLOW_ROUND_PLUS,
  },

  {
    id: 101,
    left: BLUE_SHARP_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: GREEN_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 102,
    left: BLUE_SHARP_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: BLUE_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 103,
    left: BLUE_SHARP_PLUS,
    top: BLUE_SQUARE,
    right: YELLOW_STAR,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 104,
    left: BLUE_SHARP_PLUS,
    top: PINK_CIRCLE,
    right: YELLOW_CIRCLE,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 105,
    left: BLUE_STAR,
    top: PINK_SHARP_PLUS,
    right: GREEN_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 106,
    left: YELLOW_CIRCLE,
    top: GREEN_CIRCLE,
    right: ORANGE_ROUND_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 107,
    left: YELLOW_CIRCLE,
    top: YELLOW_STAR,
    right: ORANGE_ROUND_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 108,
    left: YELLOW_CIRCLE,
    top: PINK_SHARP_PLUS,
    right: GREEN_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 109,
    left: YELLOW_CIRCLE,
    top: BLUE_SQUARE,
    right: ORANGE_SHARP_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 110,
    left: PINK_ROUND_PLUS,
    top: GREEN_SQUARE,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 111,
    left: PINK_ROUND_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: GREEN_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 112,
    left: GREEN_CIRCLE,
    top: PURPLE_STAR,
    right: YELLOW_STAR,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 113,
    left: GREEN_CIRCLE,
    top: PURPLE_STAR,
    right: BLUE_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 114,
    left: ORANGE_SHARP_PLUS,
    top: PINK_ROUND_PLUS,
    right: PINK_SHARP_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 115,
    left: ORANGE_SHARP_PLUS,
    top: PINK_SQUARE_PLUS,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 116,
    left: ORANGE_SHARP_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: ORANGE_SHARP_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 117,
    left: ORANGE_SHARP_PLUS,
    top: PINK_CIRCLE,
    right: BLUE_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 118,
    left: YELLOW_STAR,
    top: GREEN_CIRCLE,
    right: YELLOW_SQUARE_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 119,
    left: PINK_SQUARE_PLUS,
    top: BLUE_SQUARE,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 120,
    left: GREEN_SQUARE,
    top: ORANGE_ROUND_PLUS,
    right: PINK_CIRCLE,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 121,
    left: PINK_SHARP_PLUS,
    top: PINK_ROUND_PLUS,
    right: PINK_CIRCLE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 122,
    left: PURPLE_STAR,
    top: YELLOW_CIRCLE,
    right: BLUE_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 123,
    left: PURPLE_STAR,
    top: PINK_ROUND_PLUS,
    right: YELLOW_STAR,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 124,
    left: PURPLE_STAR,
    top: PURPLE_STAR,
    right: GREEN_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 125,
    left: ORANGE_ROUND_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: PINK_CIRCLE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 126,
    left: ORANGE_ROUND_PLUS,
    top: YELLOW_SQUARE_PLUS,
    right: GREEN_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 127,
    left: BLUE_SQUARE,
    top: PINK_ROUND_PLUS,
    right: YELLOW_CIRCLE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 128,
    left: BLUE_SQUARE,
    top: YELLOW_STAR,
    right: YELLOW_SQUARE_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 129,
    left: BLUE_SQUARE,
    top: PINK_SHARP_PLUS,
    right: GREEN_CIRCLE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 130,
    left: BLUE_SQUARE,
    top: PURPLE_STAR,
    right: ORANGE_ROUND_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 131,
    left: YELLOW_SQUARE_PLUS,
    top: YELLOW_CIRCLE,
    right: PURPLE_STAR,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 132,
    left: YELLOW_SQUARE_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: PINK_ROUND_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 133,
    left: PINK_CIRCLE,
    top: PINK_ROUND_PLUS,
    right: BLUE_SQUARE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 134,
    left: PINK_CIRCLE,
    top: ORANGE_SHARP_PLUS,
    right: PINK_SHARP_PLUS,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 135,
    left: PINK_CIRCLE,
    top: PINK_SHARP_PLUS,
    right: GREEN_CIRCLE,
    bottom: BLUE_SHARP_PLUS,
  },
  {
    id: 136,
    left: PINK_CIRCLE,
    top: BLUE_SQUARE,
    right: PURPLE_STAR,
    bottom: BLUE_SHARP_PLUS,
  },

  {
    id: 137,
    left: BLUE_STAR,
    top: PURPLE_STAR,
    right: PINK_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 138,
    left: YELLOW_CIRCLE,
    top: YELLOW_CIRCLE,
    right: GREEN_CIRCLE,
    bottom: BLUE_STAR,
  },
  {
    id: 139,
    left: YELLOW_CIRCLE,
    top: YELLOW_CIRCLE,
    right: ORANGE_SHARP_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 140,
    left: YELLOW_CIRCLE,
    top: YELLOW_CIRCLE,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },

  {
    id: 141,
    left: YELLOW_CIRCLE,
    top: YELLOW_STAR,
    right: YELLOW_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 142,
    left: YELLOW_CIRCLE,
    top: GREEN_SQUARE,
    right: YELLOW_CIRCLE,
    bottom: BLUE_STAR,
  },
  {
    id: 143,
    left: YELLOW_CIRCLE,
    top: BLUE_SQUARE,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 144,
    left: YELLOW_CIRCLE,
    top: YELLOW_SQUARE_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },

  {
    id: 145,
    left: PINK_ROUND_PLUS,
    top: GREEN_CIRCLE,
    right: PINK_SHARP_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 146,
    left: GREEN_CIRCLE,
    top: BLUE_STAR,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 147,
    left: GREEN_CIRCLE,
    top: BLUE_STAR,
    right: PINK_CIRCLE,
    bottom: BLUE_STAR,
  },
  {
    id: 148,
    left: GREEN_CIRCLE,
    top: GREEN_CIRCLE,
    right: PINK_ROUND_PLUS,
    bottom: BLUE_STAR,
  },

  {
    id: 149,
    left: GREEN_CIRCLE,
    top: GREEN_SQUARE,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 150,
    left: YELLOW_STAR,
    top: YELLOW_CIRCLE,
    right: ORANGE_SHARP_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 151,
    left: YELLOW_STAR,
    top: PINK_SHARP_PLUS,
    right: PINK_CIRCLE,
    bottom: BLUE_STAR,
  },
  {
    id: 152,
    left: PINK_SQUARE_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: ORANGE_SHARP_PLUS,
    bottom: BLUE_STAR,
  },

  {
    id: 153,
    left: PINK_SQUARE_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: YELLOW_STAR,
    bottom: BLUE_STAR,
  },
  {
    id: 154,
    left: PINK_SQUARE_PLUS,
    top: PINK_CIRCLE,
    right: BLUE_SQUARE,
    bottom: BLUE_STAR,
  },
  {
    id: 155,
    left: PINK_SHARP_PLUS,
    top: PINK_SQUARE_PLUS,
    right: PINK_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 156,
    left: PINK_SHARP_PLUS,
    top: PINK_SQUARE_PLUS,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },

  {
    id: 157,
    left: PINK_SHARP_PLUS,
    top: PINK_CIRCLE,
    right: PINK_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 158,
    left: PURPLE_STAR,
    top: PINK_SQUARE_PLUS,
    right: BLUE_SQUARE,
    bottom: BLUE_STAR,
  },
  {
    id: 159,
    left: PURPLE_STAR,
    top: ORANGE_ROUND_PLUS,
    right: YELLOW_CIRCLE,
    bottom: BLUE_STAR,
  },
  {
    id: 160,
    left: ORANGE_ROUND_PLUS,
    top: YELLOW_SQUARE_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: BLUE_STAR,
  },

  {
    id: 161,
    left: BLUE_SQUARE,
    top: YELLOW_CIRCLE,
    right: PURPLE_STAR,
    bottom: BLUE_STAR,
  },
  {
    id: 162,
    left: BLUE_SQUARE,
    top: PINK_ROUND_PLUS,
    right: PURPLE_STAR,
    bottom: BLUE_STAR,
  },
  {
    id: 163,
    left: PINK_CIRCLE,
    top: GREEN_SQUARE,
    right: ORANGE_SHARP_PLUS,
    bottom: BLUE_STAR,
  },
  {
    id: 164,
    left: PINK_CIRCLE,
    top: PINK_SHARP_PLUS,
    right: BLUE_SQUARE,
    bottom: BLUE_STAR,
  },

  {
    id: 165,
    left: PINK_ROUND_PLUS,
    top: GREEN_CIRCLE,
    right: PINK_SHARP_PLUS,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 166,
    left: PINK_ROUND_PLUS,
    top: PINK_SHARP_PLUS,
    right: ORANGE_ROUND_PLUS,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 167,
    left: ORANGE_SHARP_PLUS,
    top: GREEN_CIRCLE,
    right: GREEN_CIRCLE,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 168,
    left: YELLOW_STAR,
    top: ORANGE_SHARP_PLUS,
    right: GREEN_SQUARE,
    bottom: YELLOW_CIRCLE,
  },

  {
    id: 169,
    left: YELLOW_STAR,
    top: YELLOW_STAR,
    right: YELLOW_SQUARE_PLUS,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 170,
    left: PINK_SQUARE_PLUS,
    top: PINK_SHARP_PLUS,
    right: ORANGE_ROUND_PLUS,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 171,
    left: PINK_SQUARE_PLUS,
    top: PURPLE_STAR,
    right: BLUE_SQUARE,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 172,
    left: PINK_SQUARE_PLUS,
    top: YELLOW_SQUARE_PLUS,
    right: ORANGE_SHARP_PLUS,
    bottom: YELLOW_CIRCLE,
  },

  {
    id: 173,
    left: GREEN_SQUARE,
    top: GREEN_SQUARE,
    right: GREEN_SQUARE,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 174,
    left: GREEN_SQUARE,
    top: DARK_BLUE_SQUARE_PLUS,
    right: PURPLE_STAR,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 175,
    left: PINK_SHARP_PLUS,
    top: PINK_SQUARE_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 176,
    left: DARK_BLUE_SQUARE_PLUS,
    top: PINK_SQUARE_PLUS,
    right: YELLOW_STAR,
    bottom: YELLOW_CIRCLE,
  },

  {
    id: 177,
    left: PURPLE_STAR,
    top: PINK_ROUND_PLUS,
    right: PINK_SHARP_PLUS,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 178,
    left: ORANGE_ROUND_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: BLUE_SQUARE,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 179,
    left: ORANGE_ROUND_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: GREEN_SQUARE,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 180,
    left: BLUE_SQUARE,
    top: PINK_SQUARE_PLUS,
    right: BLUE_SQUARE,
    bottom: YELLOW_CIRCLE,
  },

  {
    id: 181,
    left: YELLOW_SQUARE_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: BLUE_SQUARE,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 182,
    left: YELLOW_SQUARE_PLUS,
    top: PINK_SQUARE_PLUS,
    right: ORANGE_SHARP_PLUS,
    bottom: YELLOW_CIRCLE,
  },
  {
    id: 183,
    left: PINK_ROUND_PLUS,
    top: YELLOW_STAR,
    right: ORANGE_ROUND_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 184,
    left: GREEN_CIRCLE,
    top: PINK_CIRCLE,
    right: PINK_SQUARE_PLUS,
    bottom: PINK_ROUND_PLUS,
  },

  {
    id: 185,
    left: ORANGE_SHARP_PLUS,
    top: YELLOW_STAR,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 186,
    left: ORANGE_SHARP_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: ORANGE_ROUND_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 187,
    left: YELLOW_STAR,
    top: YELLOW_SQUARE_PLUS,
    right: PINK_SQUARE_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 188,
    left: PINK_SQUARE_PLUS,
    top: PINK_ROUND_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: PINK_ROUND_PLUS,
  },

  {
    id: 189,
    left: PINK_SQUARE_PLUS,
    top: GREEN_CIRCLE,
    right: YELLOW_STAR,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 190,
    left: PINK_SQUARE_PLUS,
    top: BLUE_SQUARE,
    right: YELLOW_STAR,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 191,
    left: GREEN_SQUARE,
    top: GREEN_CIRCLE,
    right: GREEN_CIRCLE,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 192,
    left: GREEN_SQUARE,
    top: GREEN_SQUARE,
    right: PURPLE_STAR,
    bottom: PINK_ROUND_PLUS,
  },

  {
    id: 193,
    left: PINK_SHARP_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: PINK_SQUARE_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 194,
    left: DARK_BLUE_SQUARE_PLUS,
    top: YELLOW_SQUARE_PLUS,
    right: ORANGE_SHARP_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 195,
    left: DARK_BLUE_SQUARE_PLUS,
    top: YELLOW_SQUARE_PLUS,
    right: PINK_CIRCLE,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 196,
    left: DARK_BLUE_SQUARE_PLUS,
    top: PINK_CIRCLE,
    right: GREEN_SQUARE,
    bottom: PINK_ROUND_PLUS,
  },

  {
    id: 197,
    left: PURPLE_STAR,
    top: ORANGE_SHARP_PLUS,
    right: PINK_CIRCLE,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 198,
    left: PURPLE_STAR,
    top: YELLOW_STAR,
    right: ORANGE_ROUND_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 199,
    left: PURPLE_STAR,
    top: PURPLE_STAR,
    right: PURPLE_STAR,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 200,
    left: ORANGE_ROUND_PLUS,
    top: YELLOW_STAR,
    right: GREEN_CIRCLE,
    bottom: PINK_ROUND_PLUS,
  },

  {
    id: 201,
    left: BLUE_SQUARE,
    top: YELLOW_SQUARE_PLUS,
    right: ORANGE_ROUND_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 202,
    left: BLUE_SQUARE,
    top: PINK_CIRCLE,
    right: PINK_SQUARE_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 203,
    left: YELLOW_SQUARE_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: YELLOW_STAR,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 204,
    left: YELLOW_SQUARE_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: ORANGE_ROUND_PLUS,
    bottom: PINK_ROUND_PLUS,
  },

  {
    id: 205,
    left: YELLOW_SQUARE_PLUS,
    top: BLUE_SQUARE,
    right: GREEN_CIRCLE,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 206,
    left: YELLOW_SQUARE_PLUS,
    top: PINK_CIRCLE,
    right: YELLOW_SQUARE_PLUS,
    bottom: PINK_ROUND_PLUS,
  },
  {
    id: 207,
    left: GREEN_CIRCLE,
    top: PINK_CIRCLE,
    right: PINK_SQUARE_PLUS,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 208,
    left: ORANGE_SHARP_PLUS,
    top: YELLOW_STAR,
    right: PINK_CIRCLE,
    bottom: GREEN_CIRCLE,
  },

  {
    id: 209,
    left: ORANGE_SHARP_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: GREEN_SQUARE,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 210,
    left: PINK_SQUARE_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: YELLOW_STAR,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 211,
    left: PINK_SQUARE_PLUS,
    top: BLUE_SQUARE,
    right: GREEN_SQUARE,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 212,
    left: GREEN_SQUARE,
    top: GREEN_CIRCLE,
    right: BLUE_SQUARE,
    bottom: GREEN_CIRCLE,
  },

  {
    id: 213,
    left: PINK_SHARP_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: ORANGE_ROUND_PLUS,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 214,
    left: DARK_BLUE_SQUARE_PLUS,
    top: GREEN_CIRCLE,
    right: PURPLE_STAR,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 215,
    left: DARK_BLUE_SQUARE_PLUS,
    top: PINK_SHARP_PLUS,
    right: PINK_CIRCLE,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 216,
    left: DARK_BLUE_SQUARE_PLUS,
    top: PINK_CIRCLE,
    right: YELLOW_SQUARE_PLUS,
    bottom: GREEN_CIRCLE,
  },

  {
    id: 217,
    left: PURPLE_STAR,
    top: YELLOW_STAR,
    right: GREEN_SQUARE,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 218,
    left: BLUE_SQUARE,
    top: PINK_SHARP_PLUS,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 219,
    left: YELLOW_SQUARE_PLUS,
    top: ORANGE_SHARP_PLUS,
    right: PINK_SHARP_PLUS,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 220,
    left: PINK_CIRCLE,
    top: ORANGE_SHARP_PLUS,
    right: BLUE_SQUARE,
    bottom: GREEN_CIRCLE,
  },

  {
    id: 221,
    left: PINK_CIRCLE,
    top: YELLOW_SQUARE_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 222,
    left: PINK_CIRCLE,
    top: YELLOW_SQUARE_PLUS,
    right: PINK_CIRCLE,
    bottom: GREEN_CIRCLE,
  },
  {
    id: 223,
    left: ORANGE_SHARP_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: PINK_CIRCLE,
    bottom: ORANGE_SHARP_PLUS,
  },
  {
    id: 224,
    left: ORANGE_SHARP_PLUS,
    top: PURPLE_STAR,
    right: PINK_SQUARE_PLUS,
    bottom: ORANGE_SHARP_PLUS,
  },

  {
    id: 225,
    left: ORANGE_SHARP_PLUS,
    top: BLUE_SQUARE,
    right: GREEN_SQUARE,
    bottom: ORANGE_SHARP_PLUS,
  },
  {
    id: 226,
    left: PINK_SQUARE_PLUS,
    top: YELLOW_STAR,
    right: GREEN_SQUARE,
    bottom: ORANGE_SHARP_PLUS,
  },
  {
    id: 227,
    left: PINK_SQUARE_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: ORANGE_SHARP_PLUS,
  },
  {
    id: 228,
    left: PINK_SHARP_PLUS,
    top: YELLOW_STAR,
    right: ORANGE_ROUND_PLUS,
    bottom: ORANGE_SHARP_PLUS,
  },

  {
    id: 229,
    left: PURPLE_STAR,
    top: PINK_SQUARE_PLUS,
    right: PINK_CIRCLE,
    bottom: ORANGE_SHARP_PLUS,
  },
  {
    id: 230,
    left: PURPLE_STAR,
    top: BLUE_SQUARE,
    right: ORANGE_ROUND_PLUS,
    bottom: ORANGE_SHARP_PLUS,
  },
  {
    id: 231,
    left: ORANGE_ROUND_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: PURPLE_STAR,
    bottom: ORANGE_SHARP_PLUS,
  },
  {
    id: 232,
    left: ORANGE_ROUND_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: ORANGE_SHARP_PLUS,
  },

  {
    id: 233,
    left: YELLOW_STAR,
    top: YELLOW_STAR,
    right: PURPLE_STAR,
    bottom: YELLOW_STAR,
  },
  {
    id: 234,
    left: PINK_SQUARE_PLUS,
    top: BLUE_SQUARE,
    right: PINK_SHARP_PLUS,
    bottom: YELLOW_STAR,
  },
  {
    id: 235,
    left: PINK_SHARP_PLUS,
    top: PINK_SQUARE_PLUS,
    right: PINK_SHARP_PLUS,
    bottom: YELLOW_STAR,
  },
  {
    id: 236,
    left: PINK_SHARP_PLUS,
    top: PINK_SQUARE_PLUS,
    right: PURPLE_STAR,
    bottom: YELLOW_STAR,
  },

  {
    id: 237,
    left: PINK_SHARP_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: GREEN_SQUARE,
    bottom: YELLOW_STAR,
  },
  {
    id: 238,
    left: DARK_BLUE_SQUARE_PLUS,
    top: PINK_SHARP_PLUS,
    right: BLUE_SQUARE,
    bottom: YELLOW_STAR,
  },
  {
    id: 239,
    left: PURPLE_STAR,
    top: GREEN_SQUARE,
    right: PINK_CIRCLE,
    bottom: YELLOW_STAR,
  },
  {
    id: 240,
    left: PURPLE_STAR,
    top: YELLOW_SQUARE_PLUS,
    right: GREEN_SQUARE,
    bottom: YELLOW_STAR,
  },

  {
    id: 241,
    left: ORANGE_ROUND_PLUS,
    top: PINK_SQUARE_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: YELLOW_STAR,
  },
  {
    id: 242,
    left: ORANGE_ROUND_PLUS,
    top: PINK_SHARP_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: YELLOW_STAR,
  },
  {
    id: 243,
    left: GREEN_SQUARE,
    top: GREEN_SQUARE,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: PINK_SQUARE_PLUS,
  },
  {
    id: 244,
    left: GREEN_SQUARE,
    top: PURPLE_STAR,
    right: ORANGE_ROUND_PLUS,
    bottom: PINK_SQUARE_PLUS,
  },

  {
    id: 245,
    left: PINK_SHARP_PLUS,
    top: PINK_CIRCLE,
    right: PURPLE_STAR,
    bottom: PINK_SQUARE_PLUS,
  },
  {
    id: 246,
    left: YELLOW_SQUARE_PLUS,
    top: BLUE_SQUARE,
    right: PINK_CIRCLE,
    bottom: PINK_SQUARE_PLUS,
  },
  {
    id: 247,
    left: GREEN_SQUARE,
    top: YELLOW_SQUARE_PLUS,
    right: PINK_CIRCLE,
    bottom: GREEN_SQUARE,
  },
  {
    id: 248,
    left: PINK_SHARP_PLUS,
    top: DARK_BLUE_SQUARE_PLUS,
    right: PINK_SHARP_PLUS,
    bottom: GREEN_SQUARE,
  },

  {
    id: 249,
    left: DARK_BLUE_SQUARE_PLUS,
    top: PINK_SHARP_PLUS,
    right: YELLOW_SQUARE_PLUS,
    bottom: GREEN_SQUARE,
  },
  {
    id: 250,
    left: PURPLE_STAR,
    top: BLUE_SQUARE,
    right: YELLOW_SQUARE_PLUS,
    bottom: GREEN_SQUARE,
  },
  {
    id: 251,
    left: PINK_SHARP_PLUS,
    top: PINK_CIRCLE,
    right: ORANGE_ROUND_PLUS,
    bottom: PINK_SHARP_PLUS,
  },
  {
    id: 252,
    left: DARK_BLUE_SQUARE_PLUS,
    top: ORANGE_ROUND_PLUS,
    right: DARK_BLUE_SQUARE_PLUS,
    bottom: PINK_SHARP_PLUS,
  },

  {
    id: 253,
    left: ORANGE_ROUND_PLUS,
    top: BLUE_SQUARE,
    right: PURPLE_STAR,
    bottom: DARK_BLUE_SQUARE_PLUS,
  },
  {
    id: 254,
    left: BLUE_SQUARE,
    top: YELLOW_SQUARE_PLUS,
    right: BLUE_SQUARE,
    bottom: PURPLE_STAR,
  },
  {
    id: 255,
    left: PINK_CIRCLE,
    top: BLUE_SQUARE,
    right: PINK_CIRCLE,
    bottom: PURPLE_STAR,
  },
  {
    id: 256,
    left: PINK_CIRCLE,
    top: YELLOW_SQUARE_PLUS,
    right: PINK_CIRCLE,
    bottom: ORANGE_ROUND_PLUS,
  },
]

const checkpoint =
  '1, 5, 1, 2, 3, 13, 1, 6, 10, 10, 4, 5, 5, 4, 3, 8, 11, 14, 8, 5, 1, 7, 6, 14, 3, 2, 14, 19, 11, 13, 5, 15, 4, 8, 8, 19, 8, 12, 3, 7, 2, 13, 1, 8, 4, 12, 3, 4, 4, 2, 3, 20, 3, 16, 4, 13, 5, 18, 6, 14, 4, 22, 22, 8, 7, 20, 16, 10, 18, 22, 8, 17, 17, 22, 2, 2, 22, 10, 21, 2, 13, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22'
